CREATE FUNCTION excluir_usuario_associado()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM USUARIOS WHERE ID_USUARIO = OLD.ID_FOTOGRAFO;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_excluir_usuario
AFTER DELETE ON FOTOGRAFOS
FOR EACH ROW
EXECUTE FUNCTION excluir_usuario_associado();
